# Generated by Django 4.1.3 on 2022-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('Tag', models.IntegerField()),
                ('categoty', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='cheer_photo/%y/%m/%d/')),
                ('file', models.ImageField(blank=True, null=True, upload_to='cheer_file/%y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
