# Generated by Django 4.1.3 on 2022-11-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('Tag', models.IntegerField(verbose_name=2)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cheer_photo/%y/%m/%d/')),
                ('file', models.FileField(blank=True, null=True, upload_to='cheer_file/%y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categoty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category')),
            ],
        ),
    ]
